name: update-ap

on:
  deployment_status:

jobs:
  sync:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: sync activitypub
        run: |
          curl -f -X POST "https://srp.life/api/sync-feed?feedUrl=https://srp.life/feed.xml" \
            -u "${{ secrets.BRIDGE_USERNAME }}:${{ secrets.BRIDGE_PASSWORD }}"

